# Generated by Django 5.0 on 2025-11-02 04:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_class', models.CharField(choices=[('NORMAL', 'Normal'), ('PNEUMONIA_BACTERIA', 'Neumonía Bacteriana'), ('PNEUMONIA_BACTERIAL', 'Neumonía Bacterial'), ('PNEUMONIA_VIRAL', 'Neumonía Viral')], max_length=50, verbose_name='Clase Predicha')),
                ('class_id', models.IntegerField(verbose_name='ID de Clase')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Confianza')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta Raw de API')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Procesamiento (s)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando'), ('completed', 'Completado'), ('error', 'Error')], default='completed', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Severa')], max_length=20, null=True, verbose_name='Severidad')),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='Notas Médicas')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisado por Médico')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Diagnóstico',
                'verbose_name_plural': 'Resultados de Diagnósticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI/Cédula')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo de Sangre')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Historia Clínica Resumida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('findings', models.TextField(verbose_name='Hallazgos')),
                ('impression', models.TextField(verbose_name='Impresión Diagnóstica')),
                ('recommendations', models.TextField(verbose_name='Recomendaciones')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('final', 'Final'), ('revised', 'Revisado')], default='draft', max_length=20, verbose_name='Estado')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='diagnosis.diagnosisresult')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_signed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='diagnosis.patient')),
            ],
            options={
                'verbose_name': 'Reporte Médico',
                'verbose_name_plural': 'Reportes Médicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='xrays/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'dcm'])], verbose_name='Imagen de Radiografía')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción/Notas')),
                ('quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Deficiente')], default='good', max_length=20, verbose_name='Calidad de Imagen')),
                ('view_position', models.CharField(default='PA', max_length=50, verbose_name='Posición')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='Analizada')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='diagnosis.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrays_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiografía',
                'verbose_name_plural': 'Radiografías',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='xray',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diagnosis.xrayimage'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['dni'], name='diagnosis_p_dni_e721fc_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='diagnosis_p_last_na_b59593_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['patient', '-created_at'], name='diagnosis_m_patient_9826c4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['status'], name='diagnosis_m_status_91037c_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['patient', '-uploaded_at'], name='diagnosis_x_patient_e2f054_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['is_analyzed'], name='diagnosis_x_is_anal_88abe5_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisresult',
            index=models.Index(fields=['predicted_class'], name='diagnosis_d_predict_8740c5_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisresult',
            index=models.Index(fields=['status'], name='diagnosis_d_status_58d58f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisresult',
            index=models.Index(fields=['is_reviewed'], name='diagnosis_d_is_revi_23eedc_idx'),
        ),
    ]
