# Generated by Django 5.0 on 2025-11-11 23:56

import apps.diagnosis.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(help_text='Ingrese la cédula ecuatoriana de 10 dígitos', max_length=20, unique=True, validators=[apps.diagnosis.models.validate_ecuadorian_dni], verbose_name='DNI/Cédula'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de celular que comience con 09 (ejemplo: 0987654321)', max_length=20, null=True, validators=[apps.diagnosis.models.validate_ecuadorian_phone], verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('daily_patients_registered', models.IntegerField(default=0, verbose_name='Pacientes Registrados Hoy')),
                ('daily_xrays_uploaded', models.IntegerField(default=0, verbose_name='Radiografías Subidas Hoy')),
                ('daily_diagnoses_made', models.IntegerField(default=0, verbose_name='Diagnósticos Realizados Hoy')),
                ('daily_reports_generated', models.IntegerField(default=0, verbose_name='Reportes Generados Hoy')),
                ('total_patients', models.IntegerField(default=0, verbose_name='Total Pacientes')),
                ('total_xrays', models.IntegerField(default=0, verbose_name='Total Radiografías')),
                ('total_diagnoses', models.IntegerField(default=0, verbose_name='Total Diagnósticos')),
                ('total_reports', models.IntegerField(default=0, verbose_name='Total Reportes')),
                ('normal_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Normal')),
                ('pneumonia_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Neumonía')),
                ('average_system_response_time', models.FloatField(default=0.0, verbose_name='Tiempo Respuesta Promedio (s)')),
                ('api_success_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Tasa Éxito API (%)')),
                ('active_users_today', models.IntegerField(default=0, verbose_name='Usuarios Activos Hoy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estadística del Sistema',
                'verbose_name_plural': 'Estadísticas del Sistema',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='diagnosis_s_date_31532e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_diagnoses_lifetime', models.IntegerField(default=0, verbose_name='Total Diagnósticos (Histórico)')),
                ('total_reports_lifetime', models.IntegerField(default=0, verbose_name='Total Reportes (Histórico)')),
                ('total_reviews_lifetime', models.IntegerField(default=0, verbose_name='Total Revisiones (Histórico)')),
                ('lifetime_average_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Confianza Promedio Histórica')),
                ('lifetime_average_processing_time', models.FloatField(default=0.0, verbose_name='Tiempo Promedio Histórico (s)')),
                ('accuracy_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Basado en concordancia con diagnósticos confirmados', max_digits=5, verbose_name='Puntuación de Precisión')),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Basado en revisiones por pares y completitud de reportes', max_digits=5, verbose_name='Puntuación de Calidad')),
                ('specialty_focus', models.CharField(blank=True, help_text='Área donde el usuario tiene más experiencia', max_length=100, null=True, verbose_name='Enfoque de Especialidad')),
                ('first_diagnosis_date', models.DateTimeField(blank=True, null=True, verbose_name='Primera Diagnosis')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica de Rendimiento de Usuario',
                'verbose_name_plural': 'Métricas de Rendimiento de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('total_cases_analyzed', models.IntegerField(default=0, verbose_name='Total de Casos Analizados')),
                ('total_xrays_reviewed', models.IntegerField(default=0, verbose_name='Total de Radiografías Revisadas')),
                ('total_reports_generated', models.IntegerField(default=0, verbose_name='Total de Reportes Generados')),
                ('normal_cases', models.IntegerField(default=0, verbose_name='Casos Normales')),
                ('pneumonia_bacterial_cases', models.IntegerField(default=0, verbose_name='Neumonía Bacteriana')),
                ('pneumonia_viral_cases', models.IntegerField(default=0, verbose_name='Neumonía Viral')),
                ('average_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza Promedio')),
                ('high_confidence_cases', models.IntegerField(default=0, verbose_name='Casos Alta Confianza (>80%)')),
                ('low_confidence_cases', models.IntegerField(default=0, verbose_name='Casos Baja Confianza (<50%)')),
                ('mild_cases', models.IntegerField(default=0, verbose_name='Casos Leves')),
                ('moderate_cases', models.IntegerField(default=0, verbose_name='Casos Moderados')),
                ('severe_cases', models.IntegerField(default=0, verbose_name='Casos Severos')),
                ('average_processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo Promedio de Procesamiento (s)')),
                ('average_review_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo Promedio de Revisión (min)')),
                ('peer_agreement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa de Acuerdo con Pares (%)')),
                ('revision_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa de Revisión (%)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Diagnóstico',
                'verbose_name_plural': 'Estadísticas de Diagnóstico',
                'ordering': ['-period_end', '-calculated_at'],
                'indexes': [models.Index(fields=['user', '-period_end'], name='diagnosis_d_user_id_55b9d4_idx'), models.Index(fields=['period_start', 'period_end'], name='diagnosis_d_period__2b9458_idx')],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
