# Generated by Django 5.0 on 2025-11-14 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_patient_dni_alter_patient_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('CHEST_XRAY', 'Radiografía de Tórax')], default='CHEST_XRAY', max_length=50, verbose_name='Tipo de Estudio')),
                ('reason', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('clinical_notes', models.TextField(blank=True, null=True, verbose_name='Notas Clínicas Relevantes')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completada')),
            ],
            options={
                'verbose_name': 'Orden Médica',
                'verbose_name_plural': 'Órdenes Médicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='diagnosisresult',
            name='diagnosis_d_is_revi_23eedc_idx',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='analyzed_by',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='radiologist_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Radiólogo'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='radiologist_review',
            field=models.ForeignKey(blank=True, help_text='Radiólogo que revisa la predicción de IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_radiologist_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='radiologist_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Revisión Radióloga'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='treating_physician_approval',
            field=models.ForeignKey(blank=True, help_text='Médico tratante que aprueba el diagnóstico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='treating_physician_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Médico Tratante'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='radiologist_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma Radiólogo'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='radiologist_signed_by',
            field=models.ForeignKey(blank=True, help_text='Radiólogo que firma el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_radiologist_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Recepción'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Médico tratante que recibe el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis IA'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='severity',
            field=models.CharField(blank=True, choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Severa')], max_length=20, null=True, verbose_name='Severidad (Radiólogo)'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='created_by',
            field=models.ForeignKey(help_text='Radiólogo que redacta el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='diagnosisresult',
            index=models.Index(fields=['radiologist_review'], name='diagnosis_d_radiolo_6381e4_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisresult',
            index=models.Index(fields=['treating_physician_approval'], name='diagnosis_d_treatin_e937f2_idx'),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to='diagnosis.patient'),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='requested_by',
            field=models.ForeignKey(help_text='Médico tratante que solicita el estudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='medical_order',
            field=models.OneToOneField(blank=True, help_text='Orden médica asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xray_image', to='diagnosis.medicalorder'),
        ),
        migrations.AddIndex(
            model_name='medicalorder',
            index=models.Index(fields=['patient', '-created_at'], name='diagnosis_m_patient_5301f4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalorder',
            index=models.Index(fields=['status'], name='diagnosis_m_status_cbb410_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalorder',
            index=models.Index(fields=['requested_by'], name='diagnosis_m_request_8ac29b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalorder',
            index=models.Index(fields=['priority'], name='diagnosis_m_priorit_5aec3d_idx'),
        ),
    ]
