# Generated by Django 5.0 on 2025-11-15 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_medicalorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Revisado por Médico'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Médico que revisa el diagnóstico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
