# Generated by Django 5.0 on 2025-11-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_diagnosisresult_is_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicalreport',
            name='diagnosis_m_patient_9826c4_idx',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='created_by',
            field=models.ForeignKey(help_text='Médico tratante que redacta el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
