# Generated by Django 5.0 on 2025-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_remove_medicalreport_diagnosis_m_patient_9826c4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='radiologist_signed_at',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='radiologist_signed_by',
        ),
    ]
