# Generated by Django 5.0 on 2025-11-11 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audituser',
            name='registroid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Registro Id'),
        ),
    ]
